-- MySQL Script generated by MySQL Workbench
-- Wed Apr 23 19:54:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospital3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital3` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hospital3` ;

-- -----------------------------------------------------
-- Table `hospital3`.`habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital3`.`habitaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital3`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital3`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(20) NOT NULL,
  `gravedad` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni` (`dni` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital3`.`camas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital3`.`camas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `habitacion_id` INT NOT NULL,
  `paciente_id` INT NULL DEFAULT NULL,
  `estado` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `habitacion_id` (`habitacion_id` ASC) VISIBLE,
  INDEX `paciente_id` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `camas_ibfk_1`
    FOREIGN KEY (`habitacion_id`)
    REFERENCES `hospital3`.`habitaciones` (`id`),
  CONSTRAINT `camas_ibfk_2`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `hospital3`.`pacientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
